INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, false, 3, 8, 1, null, 'tester1', '$2a$10$S85ZgAciRdejsC7aVDWEduKk3Bp.QlbAAqzRUniwedOMC.E.T2KV2', 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/profile', 'asdasd', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1996-09-19', false, 0, 0, 2, null, '김도현1', '$2a$10$2FeBU6MUWa57FaBg.eOSYeyRx5xJRPl7MA3xUjwwnd78iXpYrCMqa', null, 'dojin9654', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2008-02-17', false, 0, 0, 3, null, 'asdfasdf', '$2a$10$O6qH4cQ8mYymO3Us5dtQ9OW3gZKa3kO42e8xbgDjWneMjxHXzQNpa', null, 'dojin9651', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2007-01-17', false, 0, 0, 4, null, '김도현12', '$2a$10$0KJ3HSTB3q3pk7oFJix53OtM5Vn0qvPTPMspyWDPXzLHjvdPbtUQy', null, 'dojin96541', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2008-02-18', false, 0, 0, 5, null, '김도현2', '$2a$10$WpMLx3D5ZBnn1wT4TJAozeRcpYyzzT2DrRfqBEsGnHReJ76gKfEQ.', null, 'dojin96', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2008-03-17', false, 0, 0, 6, null, 'asdfasdfa', '$2a$10$sXUFYs6/U6/ApO.TgQWhA.2OTuhA3AEgsQXk3tokTc1ImfpdOCGhC', null, 'asdf', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1999-09-13', false, 0, 0, 7, 'joohyun0913@naver.com', '야탑불주먹', '$2a$10$TLQZGWkW2UsMwPn/nw2/XuEUlcwyUE8yJcFKivB6/pLGY7gbsnSr.', null, 'qwer', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1983-05-05', false, 0, 0, 8, null, '테스트123', '$2a$10$4HUZCu0LYjL3ANyaM02ihObKRpoO92ZrC/YNwssXQKvpJobEFWq4q', null, 'aaaa123123', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1977-02-17', false, 0, 0, 9, 'joohyun0913@gmail.com', '피카츄111', '$2a$10$Ff.AnDnXomB.OtFFvUoJOe4kQcNoG6czwOqqZHKSt3U/lhrvPVK9q', 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/9/profile', 'qwert', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2009-02-18', false, 0, 0, 10, null, '도현이는 윤정이를 좋아해', '$2a$10$v1HGFyqEVPtMyaxeVlAc/OSLNqwWxokswHk5e/spoNoFReyalK6y2', null, 'rlaehgus', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, false, 0, 0, 11, null, 'tester122', '$2a$10$im5bZePo8p9rFJ7c/4606On6F3ZxOhFKBFEXGWvJU4I./6Mi/gvMG', null, 'asdfww', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, false, 0, 0, 12, null, 'deleted_e85056eb-49e6-423a-9c08-cf3f99f7ded3', null, null, null, 1);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1997-12-28', false, 0, 0, 13, null, 'hihihi123!', '$2a$10$veg0fA35v9u5oKFhmK1Xd.klE/O6FczYbZT6s6rq0kmsHSSwNtKnq', null, 'hihihi', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2023-01-02', false, 1, 1, 14, 'dojin8351@gmail.com', 'asdf1231', '$2a$10$iMxUGj2eyLkVx1on34r07.TaH1uA12HLVyoMRFb3LfQWTSHvnCDG6', 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/profile', 'asdf12', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2000-01-01', false, 0, 0, 15, null, '비번qwer1234!', '$2a$10$89.hJdxX/yDle6kH98wT0ub4wYCwdjyZFKZtB7UKrnnO.ibFIhmaW', null, 'test1', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2024-02-03', false, 0, 0, 16, null, 'asdf12', '$2a$10$CuLZ1h2Wl2/nfbDUs9YRV.ZmCe0tDuaLHsfhBBaH3PQMxw1xaUbEG', null, 'asdf123', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 17, null, '김도현_2a784179', null, null, null, 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 18, null, 'do****_847f143a', null, null, null, 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 19, null, 'deleted_89eefe8a-2dbd-4b0d-9ca0-9c504e0d9616', null, null, null, 1);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2007-01-17', false, 0, 0, 20, null, '똥가원', '$2a$10$2zEyukw7gDTgTzbJEB6Iy.cuc6mtn0QwFMFQTR53VxbX46niVZAja', null, 'qweqwe', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, false, 0, 0, 21, null, 'deleted_5599031c-f0e3-48a3-8ccf-2f1a6a19dba8', null, null, null, 1);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 22, null, 'deleted_e535e648-885f-4c1c-97f3-1bc3dd023082', null, null, null, 1);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2010-10-13', false, 0, 0, 23, null, 'asdfasdf1', '$2a$10$dCFe9BB959O2DSvdfvf1Pu42fKO.cLJzVQgxeIkuSh5CXBaSkCiZK', null, 'asdf1234', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 24, null, '준호_77e05d6e', null, null, null, 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1997-12-28', false, 0, 0, 25, null, '언지22', '$2a$10$MOAtrI/jw9EY444Vw2WFreVPkdlMyg3qjQK1jYNHSnuiGpC5/YNz2', 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/25/profile', 'qwer1234', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 26, null, '연희_54c99540', null, null, null, 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 27, null, '이종철_af65d47b', null, null, null, 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 28, null, '정다연_69667d34', null, null, null, 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES (null, true, 0, 0, 29, null, '강칠_0b7cbb7d', null, null, null, 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2024-02-02', false, 0, 0, 30, null, 'ㅁㄴㅇㅁㄴㅇ', '$2a$10$v1Sf24taLnXgwiyEw2qbfOeiho5hOfEQnGB/m.wdmnzwZTKkL1GNm', null, 'asdasdas12', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2023-03-02', false, 0, 0, 31, null, 'asdfasdfasdf', '$2a$10$kYAHRAWXXdND6lRvrexbfuQrfgSdWbvhKWldqUv/YaEuXo6ldqNJm', null, 'dojin1111', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2023-02-03', false, 0, 0, 32, null, 'asdfasdfasdfasdf', '$2a$10$ypKjLdSkzQ.tucU9v/704.JBSCnMbi4a9xgiKJeBkiu8DzKK5B8Ae', null, 'dojin12123', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1997-03-27', false, 0, 0, 33, null, 'sdfgsr', '$2a$10$WSNpo5jrXuLNEQwkbcPKxu7XPf20lSSIpZ.zqQd3qN2OXsYkGfCve', null, 'zxczxc', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1998-02-03', false, 0, 0, 34, null, '우드98', '$2a$10$uxYRhkEKN8Ib9IJhsFphEet3CGBPCPGwxV5P.5MkeuyAz69ihQrNu', null, 'dldlsdn9324', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1996-06-01', false, 0, 0, 35, null, 'moonjoonho', '$2a$10$HUbofhPPNnYjphwyotHB7.yXQeK67pWT8GVhCQZxRK8LKvgw3xU/W', null, 'moonjoonho', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1996-06-01', false, 0, 0, 36, null, 'answnsgh', '$2a$10$p/r4G6ow2/ql6BQUv8zQcexBB1gXaE0CmTtlJiQbrNuIFKxrHAC22', null, 'joonho', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1999-10-12', false, 0, 0, 37, null, 'qqqq', '$2a$10$h2NM1oXalQpW7AFpHi.eueEcfCrrEDhWxMB759VUat6owB3/wUZ.i', null, 'qkqh', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('1997-12-28', false, 0, 0, 38, null, 'A303_시연용', '$2a$10$6R8iGHIbIsQ98fU08RHFwul2n1Qt2RGYBG/BLrGr3K/d8/D8X0BxG', null, 'A303', 0);
INSERT INTO svl_rds.user_tb (birthday, social_user, streak_days, total_days, user_id, email, nickname, password, profile_image, login_id, is_deleted) VALUES ('2024-04-04', false, 1, 1, 39, null, '뭘보냐', '$2a$10$6WAVAGMT2/uPBHgjNHLE3uXlfDVF1Qrj8AF/EGPjpPsUbbvjurXSm', null, 'jujuclub28', 0);

INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (1, '4386214137', 17, 'KAKAO');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (2, 'oy7ZLmhXZ7yDbyt-vXTdD3p3evVMo2uD7-1dYOGHYRY', 18, 'NAVER');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (3, '4380866838', 19, 'KAKAO');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (4, 'UBJ7k0WjoKuCyAOfUymyN6YO5aLsgnCD3geUiiNuW98', 22, 'NAVER');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (5, '4394895520', 24, 'KAKAO');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (6, '4399920351', 26, 'KAKAO');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (7, '4399923553', 27, 'KAKAO');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (8, '4399985005', 28, 'KAKAO');
INSERT INTO svl_rds.social_login_tb (social_login_id, social_uid, user_id, provider) VALUES (9, 'RneakGwNewHgxAz_d_qLeRaKkpPgy55szjlO410avvs', 29, 'NAVER');



INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 1, 1, 'book1 description', 'book1', null, 1, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 2, 1, 'book1 description', 'book1', null, 1, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 3, 1, 'test description', 'test', null, 1, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 4, 1, '지우지 마세요', 'test 단어장', null, 0, 8);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 5, 1, 'test2 dsc', 'test2 으아아', null, 1, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (true, false, 6, 8, '오늘의 학습 단어장', '기본 폴더', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 7, 9, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 8, 10, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 9, 11, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 10, 12, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 11, 13, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 12, 14, '기본 단어장입니다', '기본 단어장', null, 0, 4);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 13, 14, '단어장2', '단어장2', null, 1, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 14, 15, '기본 단어장입니다', '기본 단어장', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 15, 16, '기본 단어장입니다', '기본 단어장', null, 0, 3);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 16, 16, '단어2', '단어2', null, 0, 4);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 17, 17, '기본', '기본단어', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 18, 20, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 19, 21, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 20, 16, '1', '1', null, 0, 4);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 21, 16, '2', '2', null, 0, 4);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 22, 16, '3', '3', null, 0, 3);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 23, 16, '4', '4', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 24, 22, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 25, 16, '10', '10', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 26, 16, '', '11', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 27, 16, '', '12', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 28, 16, '', '13', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 29, 16, '', '14', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 30, 16, '', '15', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 31, 16, '', '16', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 32, 16, '', '111', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 33, 16, '', '123123', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 34, 16, '', 'asfd', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 35, 16, '123123', '123123', null, 0, 3);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 36, 16, 'asdasd', 'asdasd', null, 0, 3);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 37, 1, '28', '재빈이형 왔다감', null, 1, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 38, 1, 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', '18', null, 1, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 39, 1, 'yes', '18', null, 1, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 40, 2, '나ㅓㅜㅏ너고ㅜ', '테스트', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 41, 2, '', '테스트2', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 42, 2, '', '테스트3', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 43, 2, 'ㅁㄴㅇ', 'ㅁㄴㅇㅁㄴㅇ', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 44, 2, 'ㅁㄴㅇ', 'ㅁㄴㅇㅁㄴ', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 45, 2, 'ㅁㄴㅇ', 'ㅁㄴㅇ', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 46, 23, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 47, 23, 'asdf', 'asdfa', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 48, 23, 'asdf', 'asdf', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 49, 23, 'a', 'a', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 50, 23, 'a', 'a', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 51, 24, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 52, 14, 'asdf', 'asdf', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 53, 14, 'asdfasfd', 'asdf', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 54, 5, 'asdf', 'asdf', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 55, 5, '1', '1', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 56, 5, '3', '2', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 57, 5, '', '4', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 58, 25, '기본 단어장입니다', '기본 단어장', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 59, 2, '안녕안녕', '안녕', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 60, 1, 'ㅗ', '단어장6', null, 1, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 61, 1, 'ㅎ', '단어장7', null, 1, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 62, 8, '', '단어장을만들었다', null, 0, 1);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 63, 25, 'hihihi', 'hihihi', null, 0, 5);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 64, 26, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 65, 27, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 66, 28, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 67, 29, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 68, 30, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 69, 31, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 70, 32, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 71, 33, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 72, 33, 'test하는 단어장', 'test1', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 73, 34, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 74, 35, '기본 단어장입니다', '기본 단어장', null, 0, 2);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, true, 75, 35, '단어장2이에요', '단어장2', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 76, 36, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 77, 37, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 78, 38, '기본 단어장입니다', '기본 단어장', null, 0, 0);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 79, 38, '시연용 테스트데이터', '0818 최종발표', null, 0, 6);
INSERT INTO svl_rds.folder_tb (is_default, is_favorite, folder_id, user_id, description, name, thumbnail, is_deleted, word_count) VALUES (false, false, 80, 39, '기본 단어장입니다', '기본 단어장', null, 0, 0);

INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 1, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/bag', 'bag', '가방', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 14, 2, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/clock', 'clock', '시계', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 3, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/glasses.jpg', 'glasses', '안경', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 4, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/laptop.jpg', 'laptop', '노트북', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 5, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/mouse.jpg', 'mouse', '마우스', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 6, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/phone.jpg', 'phone', '스마트폰', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 7, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/samsung.png', 'samsung', '삼성', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 8, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/door.jpg', 'door', '문', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 9, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/bag.jpg', 'bag', '가방', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 10, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/phone.jpg', 'phone', '스마트폰', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 11, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/door.jpg', 'door', '문', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 12, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/mouse.jpg', 'mouse', '마우스', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 13, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/hand.jpg', 'hand', '손', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 14, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/keyboard.jpg', 'keyboard', '키보드', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 15, 15, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/15/clock', 'clock', '시계', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 16, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/table.jpg', 'table', '책상', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 17, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/glasses.jpg', 'glasses', '안경', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 18, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/samsung.jpg', 'samsung', '삼성', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 2, 19, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/2/nameplate.jpg', 'nameplate', '명찰', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 20, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/nameplate.jpg', 'nameplate', '명찰', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 14, 12512345358, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/keyboard', 'keyboard', '키보드', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 14, 12512345359, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/clock', 'clock', '시계', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 14, 12512345360, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/laptop', 'laptop', '노트북', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (true, 14, 12512345361, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/mouse', 'mouse', '마우스', 2);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 14, 12512345362, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/bag', 'bag', '인식 불가', 6);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 14, 12512345363, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/table', 'table', '탁자', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (true, 16, 12512345364, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/16/clock', 'clock', '시계', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (true, 1, 12512345365, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/keyboard', 'keyboard', '키보드', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 16, 12512345366, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/16/keyboard', 'keyboard', '키보드', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 17, 12512345367, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/17/clock', 'clock', '시계', 0);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 1, 12512345368, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/1/keyboard', 'keyboard', '키보드', 2);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 16, 12512345369, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/16/clock', 'clock', '시계', 18);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 16, 12512345370, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/16/table', 'table', '탁자', 4);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 16, 12512345371, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/16/mouse', 'mouse', '마우스', 2);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 14, 12512345372, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/14/mouse', 'mouse', '마우스', 4);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 5, 12512345377, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/5/clock', 'clock', '시계', 2);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 8, 12512345378, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/8/clock', 'clock', '시계', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 35, 12512345379, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/35/clock', 'clock', '시계', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 25, 12512345380, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/25/keyboard', 'keyboard', '키보드', 2);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 25, 12512345381, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/25/laptop', 'laptop', '노트북', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 25, 12512345382, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/25/mouse', 'mouse', '마우스', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 25, 12512345383, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/25/glasses', 'glasses', '안경', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 25, 12512345384, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/25/hand', 'hand', '손', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 35, 12512345385, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/35/keyboard', 'keyboard', '키보드', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 38, 12512345386, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/38/keyboard', 'keyboard', '키보드', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 38, 12512345387, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/38/mouse', 'mouse', '마우스', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 38, 12512345388, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/38/laptop', 'laptop', '노트북', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 38, 12512345389, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/38/glasses', 'glasses', '안경', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 38, 12512345390, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/38/hand', 'hand', '손', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 38, 12512345391, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/38/door', 'door', '문', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 15, 12512345392, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/15/clock', 'clock', '시계', 1);
INSERT INTO svl_rds.word_tb (is_deleted, user_id, word_id, audio_url, image_url, name_en, name_ko, folder_count) VALUES (false, 15, 12512345393, null, 'https://svl-bucket.s3.ap-northeast-2.amazonaws.com/prod/images/15/keyboard', 'keyboard', '키보드', 1);

INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (4, 1, 20);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (4, 2, 2);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (4, 4, 7);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (4, 5, 6);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (4, 6, 5);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (4, 7, 4);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (4, 8, 3);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (12, 10, 12512345358);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (12, 11, 12512345359);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (12, 12, 12512345360);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (13, 13, 12512345361);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (13, 14, 12512345362);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (12, 15, 12512345363);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (15, 16, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (5, 17, 12512345365);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (16, 18, 12512345366);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (17, 19, 12512345367);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (16, 20, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (20, 21, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (21, 22, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (22, 23, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (23, 24, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (20, 25, 12512345366);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (21, 26, 12512345366);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (22, 27, 12512345366);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (25, 28, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (28, 29, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (30, 30, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (26, 31, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (27, 32, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (29, 33, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (31, 34, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (32, 35, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (33, 36, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (34, 37, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (35, 38, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (40, 39, 15);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (41, 40, 15);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (42, 41, 15);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (36, 42, 12512345364);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (36, 44, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (35, 45, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (34, 46, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (33, 47, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (32, 48, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (31, 49, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (30, 50, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (29, 51, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (28, 52, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (27, 53, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (26, 54, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (25, 55, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (23, 56, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (22, 57, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (21, 58, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (20, 59, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (16, 60, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (15, 61, 12512345369);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (21, 62, 12512345370);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (20, 63, 12512345370);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (36, 64, 12512345370);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (35, 65, 12512345370);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (15, 66, 12512345371);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (16, 67, 12512345371);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (53, 68, 12512345372);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (55, 69, 12512345377);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (54, 70, 12512345377);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (62, 71, 12512345378);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (63, 73, 12512345380);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (58, 74, 12512345380);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (63, 75, 12512345381);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (63, 76, 12512345382);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (63, 77, 12512345383);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (63, 78, 12512345384);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (74, 79, 12512345385);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (79, 80, 12512345386);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (79, 81, 12512345387);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (79, 82, 12512345388);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (79, 83, 12512345389);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (79, 84, 12512345390);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (79, 85, 12512345391);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (14, 86, 12512345392);
INSERT INTO svl_rds.folder_word_tb (folder_id, id, word_id) VALUES (14, 87, 12512345393);

INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (11, 53, 1, 'PENDING');
INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (23, 54, 1, 'PENDING');
INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (3, 79, 1, 'PENDING');
INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (11, 81, 9, 'PENDING');
INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (3, 82, 9, 'PENDING');
INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (6, 86, 9, 'PENDING');
INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (9, 110, 1, 'APPROVED');
INSERT INTO svl_rds.friend_tb (friend_id, id, user_id, status) VALUES (17, 111, 34, 'PENDING');

INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (1, '2025-08-18 16:58:21.000000', 1, 3);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (2, '2025-08-18 16:58:21.000000', 2, 1);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (3, '2025-08-18 16:58:21.000000', 3, 5);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (4, '2025-08-18 16:58:21.000000', 4, 2);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (5, '2025-08-18 16:58:21.000000', 5, 4);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (7, '2025-08-18 16:58:21.000000', 6, 7);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (6, '2025-08-18 16:58:21.000000', 7, 6);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (8, '2025-08-18 16:58:21.000000', 8, 11);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (9, '2025-08-18 16:58:21.000000', 9, 15);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (10, '2025-08-18 16:58:21.000000', 10, 9);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (11, '2025-08-18 16:58:21.000000', 11, 10);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (12, '2025-08-18 16:58:21.000000', 12, 14);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (13, '2025-08-18 16:58:21.000000', 13, 16);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (14, '2025-08-18 16:58:21.000000', 14, 12);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (15, '2025-08-18 16:58:21.000000', 15, 17);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (16, '2025-08-18 16:58:21.000000', 16, 13);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (17, '2025-08-18 16:58:21.000000', 17, 20);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (18, '2025-08-18 16:58:21.000000', 18, 19);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (19, '2025-08-18 16:58:21.000000', 19, 18);
INSERT INTO svl_rds.quiz_tb (problem_number, created_at, quiz_id, word_id) VALUES (20, '2025-08-18 16:58:21.000000', 20, 8);

INSERT INTO svl_rds.quiz_order_tb (id, quiz_id, user_id) VALUES (36, 2, 14);
INSERT INTO svl_rds.quiz_order_tb (id, quiz_id, user_id) VALUES (37, 7, 1);
INSERT INTO svl_rds.quiz_order_tb (id, quiz_id, user_id) VALUES (38, 2, 25);
INSERT INTO svl_rds.quiz_order_tb (id, quiz_id, user_id) VALUES (39, 2, 35);
INSERT INTO svl_rds.quiz_order_tb (id, quiz_id, user_id) VALUES (40, 19, 36);
INSERT INTO svl_rds.quiz_order_tb (id, quiz_id, user_id) VALUES (41, 8, 39);

INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-08-11 10:47:19.000000', 1, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-08-13 10:47:25.000000', 2, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-08-12 10:47:33.000000', 3, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-07-11 10:49:46.000000', 4, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-07-15 10:51:44.000000', 5, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-06-11 10:51:52.000000', 6, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-07-17 10:51:59.000000', 7, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-08-04 10:52:05.000000', 8, 1);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-08-18 00:53:42.289104', 9, 14);
INSERT INTO svl_rds.study_history_tb (created_at, study_history_id, user_user_id) VALUES ('2025-08-18 01:53:25.804060', 10, 39);
