spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbcUrl}
    username: ${jdbcUsername}
    password: ${jdbcPassword}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true