spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: ENC(V8sTvXbi0dMdKhX2T4CLyfuwVcs2j+Do05eLkDdO52Z2AJMk3q9B5txQ9/JZ3N0Eo1hPBTxE7fQdU3+SDqVRDg==)
          naver:
            redirect-uri: ENC(3U0xXnXy57dGmTAT0pi0AKeMLykbhzGvsLdZMG7dBA4K9OPZrs95mn6gbvN2MWzRJz7HwMHSE6OBAkkOUkPq8w==)
          google:
            redirect-uri: ENC(MNVzzvXthb9kFMyOgyYSwvnZm7O7AfVnOXiDNajkPe+Ae/dYKgS+xKRPI2ZUvdiuEYBvmWbZmnR+xZpvScfcEw==)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(7EYq2rZh1IIWQnSyI4bQIK/mnKV3xvXbUhWSFkkT+gFgJgAWN2StCrgjeH+MuWYaGrnkhZuUOnRrD0Ncm6gRP+JV71ySdUofUUPKfYBtEHwU4PKjtWPrcvDePwLImU9g)
    username: ENC(IYZIRo9c4O+Gs2Ya1HNnmg==)
    password: ENC(cRCXXVFIQbARhpDd5BwgAMS1c90Mj8F3)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: ENC(QXCmsRD/a5moAIQKwKSp7HT/MYVYhlVM)
      port: 6379
      password: ""

  cloud:
    aws:
      region:
        static: ENC(BtfL0sVwdELMPhALyb0MTIe46MJbeKIW)
      credentials:
        access-key: ENC(hCxkFZn+/uKzGBJN8mbssw4ZdWlxwEh6RcGEgRPx/eg=)
        secret-key: ENC(XN2PxgNxu/xBd+R+M0TIk9ILh0K5aDcSQIXswnzlt66sjSPe2j4u1+t0eVzYiBrXdZkQgks98ns=)
      s3:
        bucket-name: ENC(UOSrTPaHVuHvR9uCBSTCnZ0AqGz9wwtM)

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(Rle6A8ba1tA+ddwlW3cftmfGXEaohBj4)
    password: ENC(kYqjD2+EY1OBD3TiU46Kqcxk0oMh+H3Ff0veFrOQz3s=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  verification:
    ttl: 5m

jwt:
  secret: ${JWT_SECRET:see-vocabulary-language-ssafy-project-a303}
  access-minutes: 15m
  refresh-days: 14d

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
    com.ssafy.a303.backend: DEBUG

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

server:
  tomcat:
    max-http-form-post-size: 15MB

  ai:
    url: ENC(0FnCnLQ3VVYBWJWsF5Q3MM87EuqNtAe0D8mO0N1Dl9qtnhvx1NOeXg==)
