spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6bc8672c1f71b66bbea1e782c0a12f74
            client-secret: 4Uu4M8nOKVhsBD76oUshQMxWgHmUmisF
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
          naver:
            client-id: iujwNPkAdgGUkWSbdDuE
            client-secret: wBSNRv8bAP
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: naver
            scope:
              - nickname
          google:
            client-id: 136847245298-qiu402lhg3fbljp2vphehisdhjaft7mn.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: google
            scope:
              - openid
              - profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbcUrl}
    username: ${jdbcUsername}
    password: ${jdbcPassword}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

  cloud:
    aws:
      region:
        static: ${region}
      credentials:
        access-key: ${awsAccesskey}
        secret-key: ${awsSecretkey}
      s3:
        bucket-name: ${bucketName}

jwt:
  secret: ${JWT_SECRET:see-vocabulary-language-ssafy-project-a303}
  access-minutes: 15m
  refresh-days: 14d

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
    com.ssafy.a303.backend: DEBUG

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

server:
  tomcat:
    max-http-form-post-size: 15MB

  ai:
    url: ${aiServerUrl}
